version: '3.8'

services:
  app:
    image: ubuntu:25.04
    container_name: dev-environment
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./..:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: >
      sh -c "chmod +x /workspace/docker/startup.sh && /workspace/docker/startup.sh && tail -f /dev/null"
